# Generated by Django 3.0.2 on 2020-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_auto_20201203_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
