# Generated by Django 3.0.2 on 2020-12-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_servicepercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.OrderMeal', verbose_name='meal')),
                ('tableid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.Table')),
            ],
        ),
    ]
