# Generated by Django 3.0.2 on 2020-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_auto_20201209_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermeal',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(to='app_api.OrderMeal'),
        ),
    ]
