# Generated by Django 3.0.2 on 2020-12-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0018_auto_20201209_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermeal',
            name='name',
        ),
    ]
