# Generated by Django 3.0.2 on 2020-12-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0019_remove_ordermeal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.Meal'),
        ),
    ]
