# Generated by Django 3.0.2 on 2020-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0020_ordermeal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermeal',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='ordermeal',
            field=models.ManyToManyField(to='app_api.OrderMeal'),
        ),
    ]
