# Generated by Django 3.0.2 on 2020-12-10 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0021_auto_20201209_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 19, 39, 0, 217597), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='tableid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.Table'),
        ),
    ]
