# Generated by Django 3.0.2 on 2020-12-15 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0025_auto_20201215_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermeal',
            name='meal',
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 18, 58, 31, 495066), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 18, 58, 31, 493066), null=True),
        ),
    ]
