# Generated by Django 3.0.2 on 2020-12-15 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0029_auto_20201215_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.Meal'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 19, 10, 1, 838551), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 19, 10, 1, 837551), null=True),
        ),
    ]
